/**
 * Electron main process for FoxCode Studio.
 *
 * Responsibilities, in order of importance:
 *  1. own the single BrowserWindow (frameless, custom chrome in the renderer);
 *  2. optionally own the Python `fox serve` sidecar and relay its frames;
 *  3. expose a narrow, audited IPC surface to the preload script.
 *
 * The renderer never sees Node: `contextIsolation` + `sandbox` are on and the
 * preload exposes only the handful of channels defined in `CHANNELS`.
 */
const path = require('node:path')
const fs = require('node:fs')
const { spawn } = require('node:child_process')
const { app, BrowserWindow, ipcMain, dialog, shell, nativeTheme } = require('electron')
const { Sidecar } = require('./sidecar')
const { TerminalSessions } = require('./terminal')

const DEV_URL = process.env.VITE_DEV_SERVER_URL
const SHOT_PATH = process.env.FOXCODE_SHOT
const SHOT_CLICK = process.env.FOXCODE_SHOT_CLICK
const SHOT_EVAL = process.env.FOXCODE_SHOT_EVAL
const SHOT_EVAL_RESULT = process.env.FOXCODE_SHOT_EVAL_RESULT
const SHOT_WORKSPACE = process.env.FOXCODE_SHOT_WORKSPACE
const SHOT_RECENT_WORKSPACE = process.env.FOXCODE_SHOT_RECENT_WORKSPACE
const SHOT_EVAL_STRICT = process.env.FOXCODE_SHOT_EVAL_STRICT === '1'
const REPO_ROOT = path.resolve(__dirname, '..', '..')

function serveConfiguration() {
  if (process.env.FOXCODE_SERVE_CMD) {
    let args
    try {
      args = process.env.FOXCODE_SERVE_ARGS_JSON
        ? JSON.parse(process.env.FOXCODE_SERVE_ARGS_JSON)
        : (process.env.FOXCODE_SERVE_ARGS ?? '').split(' ').filter(Boolean)
    } catch (error) {
      console.error(`FOXCODE_SERVE_ARGS_JSON 无效：${error}`)
      args = []
    }
    return { command: process.env.FOXCODE_SERVE_CMD, args }
  }
  // Source checkouts should work on macOS without PowerShell environment
  // setup. A packaged app still accepts an explicitly installed fox_serve via
  // FOXCODE_SERVE_CMD; no system Python is silently assumed.
  if (!app.isPackaged) {
    const candidates = process.platform === 'win32'
      ? [path.join(REPO_ROOT, '.venv', 'Scripts', 'python.exe')]
      : [path.join(REPO_ROOT, '.venv', 'bin', 'python3'), path.join(REPO_ROOT, '.venv', 'bin', 'python')]
    const command = candidates.find((candidate) => fs.existsSync(candidate))
    if (command) return { command, args: ['-m', 'fox_serve', '--quiet', '--cwd', REPO_ROOT] }
  }
  return null
}

const SERVE = serveConfiguration()
const SHELL_BG = '#151517'
// Windows renders the taskbar/alt-tab image from the multi-size .ico when one
// is present; every other platform uses the PNG (generated by `npm run icon`).
const ICON_PNG = path.join(__dirname, '..', 'build', 'icon.png')
const ICON_ICO = path.join(__dirname, '..', 'build', 'icon.ico')
const WINDOW_ICON =
  process.platform === 'win32' && fs.existsSync(ICON_ICO) ? ICON_ICO : ICON_PNG

/** @type {BrowserWindow | null} */
let win = null
/** @type {Sidecar | null} */
let sidecar = null
/** Embedded terminals (pipes, no PTY) owned by this process. */
const terminals = new TerminalSessions()
/** @type {Promise<void> | null} resolved when the FOXCODE_SHOT_CLICK sequence is done */
let shotDriver = null

function send(channel, payload) {
  if (!win || win.isDestroyed()) return
  win.webContents.send(channel, payload)
}

function createSidecar() {
  if (!SERVE) return null
  // The sidecar starts inside `desktop/`, but `python -m fox_serve` resolves against
  // sys.path, so hand it the repository root unless the caller set PYTHONPATH itself.
  const child = new Sidecar(SERVE.command, SERVE.args, process.cwd(), {
    PYTHONPATH: process.env.PYTHONPATH ?? REPO_ROOT,
  })
  // One line so a failed launch is diagnosable from the terminal alone.
  console.error(`[fox serve] spawn ${SERVE.command} ${SERVE.args.join(' ')} (cwd ${process.cwd()}, PYTHONPATH ${process.env.PYTHONPATH ?? REPO_ROOT})`)
  child.on('frame', (frame) => send('host:frame', frame))
  child.on('permission', (request) => send('host:permission', request))
  child.on('transport', (status) => send('host:transport', status))
  child.on('stderr', (text) => {
    // Keep the sidecar's stderr visible in the main-process log.
    console.error(`[fox serve] ${text}`)
  })
  child.start()
  return child
}

function createWindow() {
  win = new BrowserWindow({
    width: 1440,
    height: 920,
    minWidth: 1024,
    minHeight: 660,
    show: false,
    backgroundColor: SHELL_BG,
    // 灵狐 app icon, rendered from scripts/fox-icon.html by scripts/make-icon.mjs.
    icon: WINDOW_ICON,
    title: 'FoxCode Studio · 灵狐',
    // Frameless on Windows/Linux, inset traffic lights on macOS.
    frame: false,
    titleBarStyle: process.platform === 'darwin' ? 'hiddenInset' : 'hidden',
    trafficLightPosition: { x: 16, y: 16 },
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      webSecurity: true,
      spellcheck: false,
      // Tells the preload whether a real host is available at all.
      additionalArguments: [`--foxcode-sidecar=${SERVE ? '1' : '0'}`],
    },
  })

  win.once('ready-to-show', () => {
    win?.show()
    if (SHOT_PATH) {
      // Keep the promise: captureAndQuit waits for the interaction to finish, so
      // `FOXCODE_SHOT_DELAY` means "settle after the last click", not "since launch".
      shotDriver = driveShot()
      captureAndQuit()
    }
  })

  win.on('maximize', () => send('window:maximized', true))
  win.on('unmaximize', () => send('window:maximized', false))
  win.on('closed', () => {
    // The renderer that owns the terminals is gone: their output would have
    // nowhere to go, and an orphaned shell keeps a handle on the workspace.
    terminals.dispose()
    win = null
  })

  win.webContents.setWindowOpenHandler(({ url }) => {
    if (/^https?:/.test(url)) void shell.openExternal(url)
    return { action: 'deny' }
  })

  if (DEV_URL) {
    void win.loadURL(DEV_URL)
  } else {
    void win.loadFile(path.join(__dirname, '..', 'dist', 'index.html'))
  }
}

/**
 * Optional screenshot driver: `FOXCODE_SHOT_CLICK=<substring>[+<substring>…]`
 * clicks, in order, the first button whose label contains each substring — so
 * the capture can show a live run (streaming text, tool cards) instead of the
 * empty state. Polls briefly because the renderer mounts asynchronously.
 */
function driveShot() {
  if (!SHOT_CLICK && !SHOT_EVAL && !SHOT_WORKSPACE) return Promise.resolve()
  const steps = (SHOT_CLICK ?? '')
    .split('+')
    .map((step) => step.trim())
    .filter(Boolean)

  const clickOnce = async (needle) => {
    const literal = JSON.stringify(needle)
    // 20s by default: a late step (e.g. an approval button that only appears after the
    // scripted tool batch streams in) can take much longer than the first click.
    const attempts = Math.max(1, Number(process.env.FOXCODE_SHOT_CLICK_ATTEMPTS ?? 80))
    for (let attempt = 0; attempt < attempts; attempt += 1) {
      if (!win || win.isDestroyed()) return false
      try {
        const hit = await win.webContents.executeJavaScript(
          `(() => {
             const needle = ${literal}
             const label = (b) => (b.textContent || '') + ' ' + (b.getAttribute('aria-label') || '') + ' ' + (b.getAttribute('title') || '')
             const el = [...document.querySelectorAll('button')].find((b) => label(b).includes(needle))
             if (!el) return false
             el.click()
             return true
           })()`,
        )
        if (hit) return true
      } catch (error) {
        console.error('shot click failed:', error)
        return false
      }
      await new Promise((resolve) => setTimeout(resolve, 250))
    }
    return false
  }

  return (async () => {
    await new Promise((resolve) => setTimeout(resolve, 350))
    // Deterministic real-host UI tests must get past the first-launch workspace
    // gate without automating an OS-native folder dialog. Seed exactly the same
    // persisted value that a successful picker writes, then reload once so the
    // renderer/store boot from it normally.
    if (SHOT_WORKSPACE && win && !win.isDestroyed()) {
      const persisted = JSON.stringify({
        current: SHOT_WORKSPACE,
        recent: [SHOT_WORKSPACE, SHOT_RECENT_WORKSPACE].filter(Boolean),
        aliases: {},
        hidden: [],
      })
      const loaded = new Promise((resolve) => win.webContents.once('did-finish-load', resolve))
      await win.webContents.executeJavaScript(
        `localStorage.setItem('foxcode.workspace.v1', ${JSON.stringify(persisted)}); location.reload()`,
      )
      await loaded
      await new Promise((resolve) => setTimeout(resolve, 500))
    }
    for (const needle of steps) {
      const hit = await clickOnce(needle)
      console.log(`shot click ${hit ? 'ok' : 'miss'}: ${needle}`)
      if (!hit) return
      await new Promise((resolve) => setTimeout(resolve, 350))
    }
    if (SHOT_EVAL && win && !win.isDestroyed()) {
      try {
        const value = await win.webContents.executeJavaScript(SHOT_EVAL)
        console.log(`shot eval: ${JSON.stringify(value)}`)
        if (SHOT_EVAL_RESULT) {
          const target = path.resolve(process.cwd(), SHOT_EVAL_RESULT)
          fs.mkdirSync(path.dirname(target), { recursive: true })
          fs.writeFileSync(target, `${JSON.stringify(value, null, 2)}\n`, 'utf8')
          console.log(`shot eval result written: ${target}`)
        }
      } catch (error) {
        console.error('shot eval failed:', error)
        if (SHOT_EVAL_STRICT) throw error
      }
    }
  })()
}

/**
 * Headless verification hook: `FOXCODE_SHOT=out.png electron .` renders the
 * real UI and writes a PNG, which is how this project is smoke-tested.
 * The delay starts after the optional click/eval driver has finished, so a late
 * interaction (approval button, second view) is still captured.
 */
function captureAndQuit() {
  const delay = Number(process.env.FOXCODE_SHOT_DELAY ?? 2600)
  void (async () => {
    try {
      if (shotDriver) await shotDriver
      await new Promise((resolve) => setTimeout(resolve, delay))
      if (!win) throw new Error('window is gone before capture')
      const image = await win.webContents.capturePage()
      const target = path.resolve(process.cwd(), SHOT_PATH)
      fs.mkdirSync(path.dirname(target), { recursive: true })
      fs.writeFileSync(target, image.toPNG())
      console.log(`screenshot written: ${target}`)
      app.exit(0)
    } catch (error) {
      console.error('screenshot failed:', error)
      app.exit(1)
    }
  })()
}

/* ------------------------------------------------------------------ */
/* IPC surface                                                         */
/* ------------------------------------------------------------------ */

ipcMain.handle('window:minimize', () => win?.minimize())
ipcMain.handle('window:toggle-maximize', () => {
  if (!win) return false
  if (win.isMaximized()) win.unmaximize()
  else win.maximize()
  return win.isMaximized()
})
ipcMain.handle('window:close', () => win?.close())
ipcMain.handle('window:state', () => ({
  maximized: win?.isMaximized() ?? false,
  platform: process.platform,
}))

ipcMain.handle('dialog:pick-directory', async () => {
  if (!win) return null
  const result = await dialog.showOpenDialog(win, {
    title: '选择工作区文件夹',
    buttonLabel: '作为工作区打开',
    properties: ['openDirectory', 'createDirectory'],
  })
  if (result.canceled || result.filePaths.length === 0) return null
  return result.filePaths[0]
})

ipcMain.handle('dialog:save-file', async (_event, options) => {
  if (!win) return null
  const result = await dialog.showSaveDialog(win, {
    title: options?.title ?? '保存文件',
    defaultPath: options?.defaultPath,
    filters: options?.filters,
  })
  if (result.canceled || !result.filePath) return null
  return result.filePath
})

ipcMain.handle('shell:open-external', async (_event, url) => {
  if (typeof url !== 'string' || !/^https?:/.test(url)) return false
  await shell.openExternal(url)
  return true
})

ipcMain.handle('shell:show-item', async (_event, target) => {
  if (typeof target !== 'string' || !target) return false
  // A folder opens in the file manager; a file is revealed inside its parent.
  if (fs.existsSync(target) && fs.statSync(target).isDirectory()) {
    const error = await shell.openPath(target)
    return error === ''
  }
  shell.showItemInFolder(path.resolve(target))
  return true
})

ipcMain.handle('terminal:open', async (_event, target) => {
  const cwd = path.resolve(String(target || process.cwd()))
  if (!fs.existsSync(cwd) || !fs.statSync(cwd).isDirectory()) {
    throw new Error(`终端目录不存在：${cwd}`)
  }
  let command
  let args
  if (process.platform === 'win32') {
    const shell = process.env.ComSpec || 'cmd.exe'
    if (/powershell/i.test(shell)) {
      // PowerShell 没有 `start` 内建，直接开一个带 -NoExit 的窗口。
      command = shell
      args = ['-NoExit']
    } else {
      // 关键：`cmd /K` 自己不会申请新控制台 —— GUI 进程（Electron）派生的控制台子进程
      // 默认共享/没有控制台，于是"终端"启动了却没有任何窗口。`start` 是 cmd 内建，
      // 由它去要一个新控制台窗口，窗口的工作目录继承下面的 `cwd`。
      command = shell
      args = ['/c', 'start', '', 'cmd.exe', '/K']
    }
  } else if (process.platform === 'darwin') {
    command = 'open'
    args = ['-a', 'Terminal', cwd]
  } else {
    // 各发行版的默认终端各不相同，逐个试，全失败才报错。
    const candidates = [
      ['x-terminal-emulator', []],
      ['gnome-terminal', []],
      ['konsole', []],
      ['xfce4-terminal', []],
      ['alacritty', []],
      ['xterm', []],
    ]
    for (const [name, extra] of candidates) {
      try {
        const child = spawn(name, extra, { cwd, detached: true, stdio: 'ignore' })
        await new Promise((resolve, reject) => {
          child.once('spawn', resolve)
          child.once('error', reject)
        })
        child.unref()
        return true
      } catch {
        // 装下一个
      }
    }
    throw new Error('找不到可用的终端程序（试过 x-terminal-emulator / gnome-terminal / konsole / xterm）')
  }
  const child = spawn(command, args, {
    cwd,
    detached: true,
    stdio: 'ignore',
    windowsHide: false,
  })
  await new Promise((resolve, reject) => {
    child.once('spawn', resolve)
    child.once('error', reject)
  })
  child.unref()
  return true
})

/* ------------------------------------------------------------------ */
/* Embedded terminal                                                   */
/* ------------------------------------------------------------------ */

// Output is pushed, not polled: a command can print for minutes (a dev server)
// and the renderer must not have to ask for it. `id` routes the chunk to the
// panel that owns that shell.
terminals.on('data', (payload) => send('terminal:data', payload))
terminals.on('exit', (payload) => send('terminal:exit', payload))

ipcMain.handle('terminal:start', (_event, options = {}) => {
  const cwd = path.resolve(String(options.cwd || process.cwd()))
  if (!fs.existsSync(cwd) || !fs.statSync(cwd).isDirectory()) {
    throw new Error(`终端目录不存在：${cwd}`)
  }
  return terminals.start({ cwd })
})

ipcMain.handle('terminal:write', (_event, payload = {}) => {
  const id = String(payload.id || '')
  if (!id) throw new Error('terminal:write 需要一个终端 id')
  return terminals.write(id, String(payload.data ?? ''))
})

ipcMain.handle('terminal:kill', (_event, id) => terminals.kill(String(id || '')))

ipcMain.handle('app:theme-flash', () => {
  // Brief native attention pulse when a run finishes off-screen.
  if (!win || win.isDestroyed()) return false
  if (win.isFocused()) return false
  win.flashFrame(true)
  setTimeout(() => win?.flashFrame(false), 2400)
  return true
})

ipcMain.handle('host:mode', () => ({
  sidecar: Boolean(sidecar),
  platform: process.platform,
  theme: nativeTheme.shouldUseDarkColors ? 'dark' : 'light',
}))

ipcMain.handle('host:info', async () => {
  if (!sidecar) throw new Error('没有可用的 fox serve 宿主；当前运行在内置演示模式')
  const info = await sidecar.request('host.info', {})
  return { ...info, transport: 'sidecar', sidecarConnected: true }
})

ipcMain.handle('host:sessions', async () => {
  if (!sidecar) return []
  return sidecar.request('sessions.list', {})
})

ipcMain.handle('host:command', async (_event, command) => {
  if (!sidecar) throw new Error('没有可用的 fox serve 宿主；当前运行在内置演示模式')
  if (!command || typeof command.method !== 'string') {
    throw new Error('非法命令')
  }

  // Export is the one command that needs native UI before it can run.
  if (command.method === 'session.export') {
    const format = command.params?.format === 'markdown' ? 'markdown' : 'json'
    const target = await dialog.showSaveDialog(win, {
      title: '导出会话',
      defaultPath: command.params?.path || `session.${format}`,
      filters:
        format === 'json'
          ? [{ name: 'JSON', extensions: ['json'] }]
          : [{ name: 'Markdown', extensions: ['md'] }],
    })
    if (target.canceled || !target.filePath) return { canceled: true }
    return sidecar.request('session.export', { format, path: target.filePath })
  }

  return sidecar.request(command.method, command.params ?? {})
})

/* ------------------------------------------------------------------ */
/* Lifecycle                                                           */
/* ------------------------------------------------------------------ */

// Single instance: a second launch focuses the existing window instead.
if (!app.requestSingleInstanceLock()) {
  app.quit()
} else {
  app.on('second-instance', () => {
    if (!win) return
    if (win.isMinimized()) win.restore()
    win.focus()
  })

  app.whenReady().then(() => {
    sidecar = createSidecar()
    createWindow()

    app.on('activate', () => {
      if (BrowserWindow.getAllWindows().length === 0) createWindow()
    })
  })

  app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') app.quit()
  })

  app.on('before-quit', () => {
    terminals.dispose()
    sidecar?.stop()
    sidecar = null
  })
}
